In [25]:
import pandas as pd
import numpy as np
from copy import deepcopy

k=3
df=pd.read_csv("data.csv")
df

x    y
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  6.1  3.8
9  6.0  3.0

In [26]:
x1=df['x'].values
x2=df['y'].values
X=np.array(list(zip(x1,x2)))

In [27]:
C_x = [6.2, 6.6 ,6.5]
C_y = [3.2, 3.7, 3.0]
Centroid=np.array(list(zip(C_x,C_y)))
print(Centroid.shape)
Centroid_old=np.zeros(Centroid.shape)
Centroid_old

(3, 2)


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
def euclidean(a,b,ax=1):
    return np.linalg.norm(a-b,axis=ax)

In [29]:
clusters=np.zeros(len(X))
clusters

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
error=euclidean(Centroid,Centroid_old,None)
print(error)

12.53714481052205


In [31]:
iterr=0
while error!=0:
    iterr=iterr+1
    for i in range(len(X)):
        distances=euclidean(X[i],Centroid)
        cluster=np.argmin(distances)
        clusters[i]=cluster
    Centroid_old=deepcopy(Centroid)
    
    for p in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j]==p ]
        Centroid[p]=np.mean(points)
    print("\n Centre of the clusters after ", iterr," Iteration \n", Centroid)
    error = euclidean(Centroid, Centroid_old, None)
    print("Error  ... ",error)    


 Centre of the clusters after  1  Iteration 
 [[4.125 4.125]
 [4.9   4.9  ]
 [4.7   4.7  ]]
Error  ...  3.952372705097534

 Centre of the clusters after  2  Iteration 
 [[3.925      3.925     ]
 [4.9        4.9       ]
 [4.51666667 4.51666667]]
Error  ...  0.38369548110737833

 Centre of the clusters after  3  Iteration 
 [[3.925      3.925     ]
 [4.9        4.9       ]
 [4.51666667 4.51666667]]
Error  ...  0.0
